language: objective-c
osx_image: xcode8.1

env:
   global:

   - PROJECT="StringInputValidator.xcodeproj"
   - IOS_SCHEME="StringInputValidator"
   - IOS_SDK=iphonesimulator10.1

   matrix:
   - DESTINATION="OS=10.0,name=iPhone 6s" SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"
   - DESTINATION="OS=10.1,name=iPhone 7"  SDK="$IOS_SDK" SCHEME="$IOS_SCHEME" RUN_TESTS="YES"

script:
- set -o pipefail

- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild analyze test -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  else
      xcodebuild build analyze -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi

# Build for reporting test coverage
- if [ $RUN_TESTS == "YES" ]; then
      xcodebuild test -project StringInputValidator.xcodeproj -scheme StringInputValidator -destination "platform=iOS Simulator,name=iPhone 7" CODE_SIGNING_REQUIRED=NO | xcpretty -c;
  fi

after_success:
  - bash <(curl -s https://codecov.io/bash)